name: cloudhw-release
services:
  cloudhw-be: 
    container_name: cloudhw-be
    build:
      context: cloudhw-BE
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      POSTGRES_HOST: cloudhw-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIANCE: ${JWT_AUDIANCE}
      JWT_KEY: ${JWT_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_NAME: ${ADMIN_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
    networks: 
      - cloudhw-network

  cloudhw-fe:
    container_name: cloudhw-fe
    build:
      context: cloudhw-FE
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "82:80"
    networks: 
      - cloudhw-network
    environment:
      - BACKEND_URL=${BACKEND_URL}

  cloudhw-db:
    image: postgres
    container_name: cloudhw-db
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - cloudhw-db-data:/var/lib/postgresql/data
    networks: 
      - cloudhw-network

  cloudhw-pgadmin:
    image: dpage/pgadmin4
    container_name: cloudhw-pgadmin
    restart: unless-stopped
    ports:
      - "5055:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - cloudhw-pgadmin-data:/var/lib/pgadmin
    networks:
      - cloudhw-network

volumes:
  cloudhw-db-data:
  cloudhw-pgadmin-data:

networks:
  cloudhw-network:
    driver: bridge