runtime: nodejs20

handlers:
- url: /(.*\.(js|css|png|jpg|svg|ico|woff|woff2|ttf|eot))$
  static_files: dist/cloudhw-fe/browser/\1
  upload: dist/cloudhw-fe/browser/(.*\.(js|css|png|jpg|svg|ico|woff|woff2|ttf|eot))$

- url: /.*
  static_files: dist/cloudhw-fe/browser/index.html
  upload: dist/cloudhw-fe/browser/index.html