runtime: custom
env: flex
service: api

beta_settings:
  cloud_sql_instances: "${GCP_CLOUDSQL_CONNECTION_NAME}"

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 30
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 10

env_variables:
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  JWT_ISSUER: "${JWT_ISSUER}"
  JWT_AUDIANCE: "${JWT_AUDIANCE}"
  JWT_KEY: "${JWT_KEY}"
  ADMIN_EMAIL: "${ADMIN_EMAIL}"
  ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
  ADMIN_NAME: "${ADMIN_NAME}"
  FRONTEND_URL: "${FRONTEND_URL}"
  ASPNETCORE_AllowedHosts: "${ASPNETCORE_AllowedHosts}"
  SMTP_HOST: "${SMTP_HOST}"
  SMTP_PORT: "${SMTP_PORT}"
  SMTP_USER: "${SMTP_USER}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SMTP_FROM: "${SMTP_FROM}"
