"""
PikVjú Photo Album – Locust load test
======================================
Two user types run in parallel:

  RegisteringUser  (weight 2, ~25%)
    Simulates new visitors: public browsing + registration + failed login.
    Rate limiting is disabled, so registration is exercised under full load.

  PhotoAlbumUser   (weight 6, ~75%)
    Simulates authenticated users: full album & picture workflow, auth cycles
    (logout → re-login), profile management, sharing.

Prerequisites
-------------
1. Run seed_users.py once to create and confirm test accounts → users.json
2. Start the test:

    locust -f locustfile.py --host=https://api-dot-YOUR_PROJECT.appspot.com

   Headless (GCP VM / CI):
    locust -f locustfile.py \
           --host=https://api-dot-YOUR_PROJECT.appspot.com \
           --headless --users=80 --spawn-rate=8 --run-time=15m \
           --html=report.html --csv=results

   ScalingDemoShape is active by default – it runs the ramp-up/ramp-down
   pattern automatically and stops after ~15 minutes.

Notes on auth
-------------
The backend issues a 15-minute JWT + an HttpOnly refresh-token cookie
(path /api/user).  PhotoAlbumUser refreshes the token transparently 1 min
before expiry and supports full logout → re-login cycles.
"""

import io
import json
import logging
import random
import string
import time
from pathlib import Path

from locust import HttpUser, LoadTestShape, between, task

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Test-user pool (generated by seed_users.py)
# ---------------------------------------------------------------------------

_USERS_FILE = Path(__file__).parent / "users.json"


def _load_users() -> list[dict]:
    if not _USERS_FILE.exists():
        raise FileNotFoundError(
            f"users.json not found at {_USERS_FILE}.\n"
            "Run seed_users.py first, or copy users.example.json to users.json."
        )
    with open(_USERS_FILE) as fh:
        users = json.load(fh)
    if not users:
        raise ValueError("users.json is empty – add at least one test user.")
    return users


TEST_USERS: list[dict] = _load_users()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _rand_str(n: int = 8) -> str:
    return "".join(random.choices(string.ascii_lowercase + string.digits, k=n))


def _make_jpeg(width: int = 300, height: int = 300) -> bytes:
    try:
        from PIL import Image  # type: ignore
    except ImportError:
        raise ImportError("Pillow is required: pip install Pillow")

    color = (random.randint(30, 220), random.randint(30, 220), random.randint(30, 220))
    img = Image.new("RGB", (width, height), color=color)
    for _ in range(80):
        img.putpixel(
            (random.randint(0, width - 1), random.randint(0, height - 1)),
            (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)),
        )
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=75)
    buf.seek(0)
    return buf.read()


# ---------------------------------------------------------------------------
# RegisteringUser – anonymous / new-visitor flow
# ---------------------------------------------------------------------------

class RegisteringUser(HttpUser):
    """
    Simulates a visitor who discovers the app, browses public content,
    registers an account, and tries to log in (will fail – email not confirmed,
    but exercises the full auth pipeline under load).

    weight=2 → ~25% of total virtual users
    """

    weight = 2
    wait_time = between(1, 4)

    # -----------------------------------------------------------------------
    # Public browsing
    # -----------------------------------------------------------------------

    @task(5)
    def browse_public_albums(self) -> None:
        self.client.get("/api/album/public", name="/api/album/public [GET]")

    @task(3)
    def search_albums(self) -> None:
        q = random.choice(["a", "e", "o", "photo", "trip", "album", "vac", "ny"])
        self.client.get(f"/api/album/search?q={q}", name="/api/album/search [GET]")

    @task(2)
    def view_public_album_detail(self) -> None:
        """Fetch a specific public album by browsing the list first."""
        resp = self.client.get("/api/album/public", name="/api/album/public [GET]")
        if resp.status_code == 200:
            albums = resp.json()
            if albums:
                album = random.choice(albums)
                self.client.get(
                    f"/api/album/{album['id']}",
                    name="/api/album/{id} [GET]",
                )

    @task(1)
    def view_public_album_cover(self) -> None:
        resp = self.client.get("/api/album/public", name="/api/album/public [GET]")
        if resp.status_code == 200:
            albums = [a for a in resp.json() if a.get("coverPictureId")]
            if albums:
                album = random.choice(albums)
                self.client.get(
                    f"/api/album/{album['id']}/cover",
                    name="/api/album/{id}/cover [GET]",
                )

    # -----------------------------------------------------------------------
    # Registration flow
    # -----------------------------------------------------------------------

    @task(2)
    def register_new_account(self) -> None:
        """
        Register a fresh random account.
        Email confirmation is not completed, but the endpoint is fully exercised
        (user created in DB, confirmation email attempted via SMTP).
        """
        email = f"lt_{_rand_str(10)}@loadtest.invalid"
        self.client.post(
            "/api/user/register",
            json={
                "email":    email,
                "password": "LoadTest@2026!",
                "name":     f"LT Visitor {_rand_str(4)}",
            },
            name="/api/user/register [POST]",
        )

    @task(1)
    def login_with_wrong_password(self) -> None:
        """Exercises the login rejection path (401) under load."""
        self.client.post(
            "/api/user/login",
            json={"email": f"nobody_{_rand_str(6)}@loadtest.invalid", "password": "wrong"},
            name="/api/user/login [POST – 401]",
        )


# ---------------------------------------------------------------------------
# PhotoAlbumUser – authenticated user flow
# ---------------------------------------------------------------------------

class PhotoAlbumUser(HttpUser):
    """
    Simulates a confirmed user: logs in, manages albums and pictures,
    performs auth cycles, and shares content with other users.

    weight=6 → ~75% of total virtual users
    """

    weight = 6
    wait_time = between(0.5, 2.5)

    token: str | None = None
    token_expires_at: float = 0.0
    album_ids: list[str]
    picture_ids: list[str]
    other_user_ids: list[str]

    # -----------------------------------------------------------------------
    # Lifecycle
    # -----------------------------------------------------------------------

    def on_start(self) -> None:
        self.album_ids      = []
        self.picture_ids    = []
        self.other_user_ids = []
        creds          = random.choice(TEST_USERS)
        self.email     = creds["email"]
        self.password  = creds["password"]
        self._login()

    def on_stop(self) -> None:
        if not self.token:
            return
        for album_id in self.album_ids[:5]:
            self.client.delete(
                f"/api/album/{album_id}",
                headers=self._auth,
                name="/api/album/{id} [DELETE]",
            )
        self.client.post("/api/user/logout", headers=self._auth, name="/api/user/logout [POST]")

    # -----------------------------------------------------------------------
    # Auth helpers
    # -----------------------------------------------------------------------

    def _login(self) -> None:
        resp = self.client.post(
            "/api/user/login",
            json={"email": self.email, "password": self.password, "rememberMe": True},
            name="/api/user/login [POST]",
        )
        if resp.status_code == 200:
            self.token            = resp.json().get("token")
            self.token_expires_at = time.time() + 14 * 60
        else:
            logger.error("Login failed for %s: %s %s", self.email, resp.status_code, resp.text[:200])

    def _ensure_token(self) -> None:
        if time.time() < self.token_expires_at:
            return
        resp = self.client.post("/api/user/refresh-token", name="/api/user/refresh-token [POST]")
        if resp.status_code == 200:
            self.token            = resp.json().get("token")
            self.token_expires_at = time.time() + 14 * 60
        else:
            self._login()

    @property
    def _auth(self) -> dict:
        self._ensure_token()
        return {"Authorization": f"Bearer {self.token}"}

    # -----------------------------------------------------------------------
    # Auth cycle tasks
    # -----------------------------------------------------------------------

    @task(2)
    def logout_and_relogin(self) -> None:
        """Full auth cycle: logout → login. Tests both endpoints under load."""
        if not self.token:
            return
        resp = self.client.post("/api/user/logout", headers=self._auth, name="/api/user/logout [POST]")
        if resp.status_code == 200:
            self.token            = None
            self.token_expires_at = 0.0
            self._login()

    @task(1)
    def explicit_token_refresh(self) -> None:
        """Force a token refresh regardless of expiry (tests the refresh endpoint)."""
        self.token_expires_at = 0.0
        self._ensure_token()

    # -----------------------------------------------------------------------
    # User profile
    # -----------------------------------------------------------------------

    @task(3)
    def get_own_profile(self) -> None:
        if not self.token:
            return
        self.client.get("/api/user/me", headers=self._auth, name="/api/user/me [GET]")

    @task(1)
    def update_own_profile(self) -> None:
        if not self.token:
            return
        self.client.put(
            "/api/user/me",
            json={"name": f"LT User {_rand_str(4)}", "email": self.email},
            headers=self._auth,
            name="/api/user/me [PUT]",
        )

    @task(2)
    def search_users(self) -> None:
        """Discover other users to feed the share task."""
        if not self.token:
            return
        q = random.choice(["loadtest", "lt", "user", "test", "a"])
        resp = self.client.get(
            f"/api/user/search?q={q}",
            headers=self._auth,
            name="/api/user/search [GET]",
        )
        if resp.status_code == 200:
            for u in resp.json():
                uid = u.get("id")
                if uid and uid not in self.other_user_ids:
                    self.other_user_ids.append(uid)

    @task(1)
    def view_public_profile(self) -> None:
        """Fetch another user's public profile by ID."""
        if not self.token or not self.other_user_ids:
            return
        uid = random.choice(self.other_user_ids)
        self.client.get(
            f"/api/user/public/{uid}",
            headers=self._auth,
            name="/api/user/public/{id} [GET]",
        )

    # -----------------------------------------------------------------------
    # Public browsing (authenticated users also browse)
    # -----------------------------------------------------------------------

    @task(4)
    def browse_public_albums(self) -> None:
        self.client.get("/api/album/public", name="/api/album/public [GET]")

    @task(2)
    def search_albums_public(self) -> None:
        q = random.choice(["a", "e", "o", "photo", "trip", "album", "ny", "vac"])
        self.client.get(f"/api/album/search?q={q}", name="/api/album/search [GET]")

    # -----------------------------------------------------------------------
    # Albums – read
    # -----------------------------------------------------------------------

    @task(5)
    def list_my_albums(self) -> None:
        if not self.token:
            return
        resp = self.client.get("/api/album/my", headers=self._auth, name="/api/album/my [GET]")
        if resp.status_code == 200:
            for a in resp.json():
                aid = a.get("id")
                if aid and aid not in self.album_ids:
                    self.album_ids.append(aid)

    @task(2)
    def list_shared_albums(self) -> None:
        if not self.token:
            return
        self.client.get("/api/album/shared", headers=self._auth, name="/api/album/shared [GET]")

    @task(3)
    def view_album_detail(self) -> None:
        if not self.album_ids:
            return
        self.client.get(
            f"/api/album/{random.choice(self.album_ids)}",
            headers=self._auth,
            name="/api/album/{id} [GET]",
        )

    @task(2)
    def get_album_cover(self) -> None:
        if not self.album_ids:
            return
        self.client.get(
            f"/api/album/{random.choice(self.album_ids)}/cover",
            headers=self._auth,
            name="/api/album/{id}/cover [GET]",
        )

    @task(1)
    def get_album_shares(self) -> None:
        if not self.token or not self.album_ids:
            return
        self.client.get(
            f"/api/album/{random.choice(self.album_ids)}/shares",
            headers=self._auth,
            name="/api/album/{id}/shares [GET]",
        )

    # -----------------------------------------------------------------------
    # Albums – write
    # -----------------------------------------------------------------------

    @task(3)
    def create_album(self) -> None:
        if not self.token:
            return
        resp = self.client.post(
            "/api/album",
            json={
                "name":        f"LT-{_rand_str(6)}",
                "description": f"Load-test album {time.strftime('%H:%M:%S')}",
                "isPublic":    random.random() < 0.4,
            },
            headers=self._auth,
            name="/api/album [POST]",
        )
        if resp.status_code == 200:
            aid = resp.json().get("id")
            if aid:
                self.album_ids.append(aid)
                self._upload_picture(aid)

    @task(1)
    def update_album(self) -> None:
        if not self.token or not self.album_ids:
            return
        self.client.put(
            f"/api/album/{random.choice(self.album_ids)}",
            json={
                "name":        f"LT-updated-{_rand_str(4)}",
                "description": "Updated during load test",
                "isPublic":    random.choice([True, False]),
            },
            headers=self._auth,
            name="/api/album/{id} [PUT]",
        )

    @task(1)
    def share_then_unshare_album(self) -> None:
        if not self.token or not self.album_ids or not self.other_user_ids:
            return
        album_id       = random.choice(self.album_ids)
        target_user_id = random.choice(self.other_user_ids)
        resp = self.client.post(
            f"/api/album/{album_id}/share",
            json={"userId": target_user_id},
            headers=self._auth,
            name="/api/album/{id}/share [POST]",
        )
        if resp.status_code == 200:
            self.client.delete(
                f"/api/album/{album_id}/share/{target_user_id}",
                headers=self._auth,
                name="/api/album/{id}/share/{uid} [DELETE]",
            )

    # -----------------------------------------------------------------------
    # Pictures – read
    # -----------------------------------------------------------------------

    @task(6)
    def list_pictures(self) -> None:
        if not self.album_ids:
            return
        album_id = random.choice(self.album_ids)
        resp = self.client.get(
            f"/api/picture/album/{album_id}",
            headers=self._auth,
            name="/api/picture/album/{id} [GET]",
        )
        if resp.status_code == 200:
            for p in resp.json():
                pid = p.get("id")
                if pid and pid not in self.picture_ids:
                    self.picture_ids.append(pid)

    @task(5)
    def get_thumbnails(self) -> None:
        if not self.album_ids:
            return
        self.client.get(
            f"/api/picture/album/{random.choice(self.album_ids)}/thumbnails",
            headers=self._auth,
            name="/api/picture/album/{id}/thumbnails [GET]",
        )

    @task(4)
    def view_picture_thumbnail(self) -> None:
        if not self.picture_ids:
            return
        self.client.get(
            f"/api/picture/{random.choice(self.picture_ids)}/thumbnail",
            headers=self._auth,
            name="/api/picture/{id}/thumbnail [GET]",
        )

    @task(3)
    def view_picture_fullres(self) -> None:
        if not self.picture_ids:
            return
        self.client.get(
            f"/api/picture/{random.choice(self.picture_ids)}/data",
            headers=self._auth,
            name="/api/picture/{id}/data [GET]",
        )

    @task(1)
    def get_picture_metadata(self) -> None:
        if not self.picture_ids:
            return
        self.client.get(
            f"/api/picture/{random.choice(self.picture_ids)}",
            headers=self._auth,
            name="/api/picture/{id} [GET]",
        )

    # -----------------------------------------------------------------------
    # Pictures – write
    # -----------------------------------------------------------------------

    @task(3)
    def upload_picture(self) -> None:
        if not self.token or not self.album_ids:
            return
        self._upload_picture(random.choice(self.album_ids))

    def _upload_picture(self, album_id: str) -> str | None:
        image_bytes = _make_jpeg()
        resp = self.client.post(
            f"/api/picture/album/{album_id}",
            files={"file": (f"lt_{_rand_str(6)}.jpg", io.BytesIO(image_bytes), "image/jpeg")},
            headers=self._auth,
            name="/api/picture/album/{id} [POST]",
        )
        if resp.status_code == 200:
            pid = resp.json().get("id")
            if pid:
                self.picture_ids.append(pid)
            return pid
        return None

    @task(1)
    def rename_picture(self) -> None:
        if not self.token or not self.picture_ids:
            return
        self.client.patch(
            f"/api/picture/{random.choice(self.picture_ids)}/name",
            json={"name": f"lt_{_rand_str(8)}"},
            headers=self._auth,
            name="/api/picture/{id}/name [PATCH]",
        )

    @task(1)
    def set_album_cover(self) -> None:
        if not self.token or not self.album_ids or not self.picture_ids:
            return
        self.client.put(
            f"/api/album/{random.choice(self.album_ids)}/cover",
            json={"pictureId": random.choice(self.picture_ids)},
            headers=self._auth,
            name="/api/album/{id}/cover [PUT]",
        )

    @task(1)
    def download_album_zip(self) -> None:
        if not self.album_ids:
            return
        self.client.get(
            f"/api/album/{random.choice(self.album_ids)}/download",
            headers=self._auth,
            name="/api/album/{id}/download [GET]",
        )

    @task(1)
    def delete_oldest_picture(self) -> None:
        """Prune oldest picture to avoid runaway DB growth during long runs."""
        if not self.token or len(self.picture_ids) < 10:
            return
        pic_id = self.picture_ids.pop(0)
        self.client.delete(
            f"/api/picture/{pic_id}",
            headers=self._auth,
            name="/api/picture/{id} [DELETE]",
        )


# ---------------------------------------------------------------------------
# Load shape
# ---------------------------------------------------------------------------

class ScalingDemoShape(LoadTestShape):
    """
    Staged ramp pattern (~15 min) to demonstrate both scale-out and scale-in.

    Phase 1  0–2 min    10 users   warm-up          1 instance sufficient
    Phase 2  2–5 min    50 users   moderate load  → 2nd instance spins up
    Phase 3  5–9 min   100 users   peak load      → 3–5 instances active
    Phase 4  9–12 min   20 users   decreasing     → scale-in begins
    Phase 5 12–15 min    5 users   cool-down      → back to 1 instance

    User split at 100 VUs: ~25 RegisteringUser + ~75 PhotoAlbumUser
    """

    stages = [
        {"duration":  120, "users":  10, "spawn_rate":  2},
        {"duration":  300, "users":  50, "spawn_rate":  8},
        {"duration":  540, "users": 100, "spawn_rate": 10},
        {"duration":  720, "users":  20, "spawn_rate": 20},
        {"duration":  900, "users":   5, "spawn_rate": 10},
    ]

    def tick(self) -> tuple[int, float] | None:
        run_time = self.get_run_time()
        for stage in self.stages:
            if run_time < stage["duration"]:
                return stage["users"], stage["spawn_rate"]
        return None
